version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "9000:9000"
    environment:
      - APP_NAME=Quiz API
    volumes:
      - ./api:/app
    networks:
      - quiz-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - API_URL=https://veggie-quiz.onrender.com  # For local development
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://veggie-quiz.onrender.com
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge